import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";

import styles from "../styles/Home.module.scss";

const Home: NextPage = () => {
  let router = useRouter();

  let question =
    router.locale === "en-US"
      ? " Which of the below statements about electricity is not true?"
      : router.locale === "fr"
      ? "Laquelle des affirmations ci-dessous concernant l'électricité n'est pas vraie ?"
      : "";

  let card1 =
    router.locale === "en-US"
      ? " Electricity is measured in units called watts"
      : router.locale === "fr"
      ? "L'électricité est mesurée en unités appelées watts"
      : "";

  let card2 =
    router.locale === "en-US"
      ? " Electricity flows at the speed of light."
      : router.locale === "fr"
      ? "L'électricité circule à la vitesse de la lumière."
      : "";

  let card3 =
    router.locale === "en-US"
      ? "Electricity is a primary energy source."
      : router.locale === "fr"
      ? "L'électricité est une source d'énergie primaire."
      : "";

  return (
    <div className="hello">
      <Head>
        <title>Task</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.lang_container}>
        <ul>
          {router.locales?.map((locale) => (
            <li key={locale}>
              <Link href={router.asPath} locale={locale}>
                <a>{locale}</a>
              </Link>
            </li>
          ))}
        </ul>
      </div>

      <div className={styles.task_container}>
        <div className={styles.container}>
          <div className={styles.question_container}>
            <p>{question}</p>
          </div>
          <div className={styles.card_container}>
            <div className={styles.card1}>
              <div className={styles.input}></div>
              <p>{card1}</p>
            </div>
            <div className={styles.card2}>
              <div className={styles.input}></div>
              <p>{card2}</p>
            </div>
            <div className={styles.card3}>
              <div className={styles.input3}></div>
              <p>{card3}</p>
            </div>
          </div>
        </div>
      
      </div>
      
    </div>
  );
};

export default Home;
