import type { NextPage } from "next";
import Head from "next/head";

import styles from "../styles/Home.module.scss";


const Home: NextPage = () => {

  return (
    <div className="hello">
      <Head>
        <title>Task</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     

      <div className={styles.task_container}>
        <div className={styles.container}>
          <div className={styles.question_container}>
            <p >
              Which of the below statements about electricity is not true?
            </p>
          </div>
          <div className={styles.card_container}>
            <div  className={styles.card1}>
              <div className={styles.input}></div>
             <p >
                Electricity is measured in units called watts.
              </p>
            </div>
            <div  className={styles.card2}>
              <div className={styles.input}></div>
              <p >
                Electricity flows at the speed of light.
              </p>
            </div>
            <div  className={styles.card3}>
              <div className={styles.input3}></div>
              <p >
                Electricity is a primary energy source.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Home;
